gnuplot graficoTempiVF.gp
gnuplot graficoDeleghe.gp
gnuplot graficoDelegheTotali.gp
gnuplot graficoData.gp

gnuplot graficoDataDiversaFDS_3.gp
gnuplot graficoDataDiversaFDS_3_zoom.gp
gnuplot graficoDataDiversaFDS_10.gp
gnuplot graficoDataDiversaFDS_10_zoom.gp
gnuplot graficoDataDiversaFDS_25.gp
gnuplot graficoDataDiversaFDS_25_zoom.gp

gnuplot graficoRidondanza.gp
gnuplot graficoTempiRitornoDeleghe.gp
gnuplot graficoDelegheAttive.gp

gnuplot graficoTempiVFDiversaPop.gp
gnuplot graficoTempiVFDiversaPop_zoom.gp

gnuplot graficoTempiVF_Fp5.gp
gnuplot graficoTempiVF_Fp5_zoom.gp
gnuplot graficoTempiVF_Fp10.gp
gnuplot graficoTempiVF_Fp10_zoom.gp
gnuplot graficoTempiVF_Fp50.gp
gnuplot graficoTempiVF_Fp50_zoom.gp

gnuplot graficoPercCompletiMultiHop.gp

gnuplot graficoTempiVFMultiHopPerc.gp
gnuplot graficoDelegheMultiHopPerc.gp

gnuplot graficoRidondanza_multiHop_10perc.gp
gnuplot graficoRidondanza_multiHop_25perc.gp
gnuplot graficoRidondanza_multiHop_50perc.gp
gnuplot graficoRidondanza_multiHop_75perc.gp
gnuplot graficoRidondanza_multiHop_100perc.gp

gnuplot graficoDelegheAttive_multiHop_10perc.gp
gnuplot graficoDelegheAttive_multiHop_25perc.gp
gnuplot graficoDelegheAttive_multiHop_50perc.gp
gnuplot graficoDelegheAttive_multiHop_75perc.gp
gnuplot graficoDelegheAttive_multiHop_100perc.gp

